project:
  type: website
  output-dir: docs

website:
  title: "mecanizacao"
  google-analytics: "G-8L8YC0LJJY"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true